import { ReactNode } from 'react';
import '@/styles/global.css';
import Header from '@/components/layout/header';
import Profile from '@/components/ui/profile';
import TagsMenu from '@/components/menus/TagsMenu';
import { fetchTags } from '@/lib/notion/api/fetchTags';

export const metadata = {
  title: 'jhsonnn | 손지형의 블로그',
  description: 'Generated by create next app',
};

interface LayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: LayoutProps) {
  const tags = await fetchTags();

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
      </head>
      <body className="dark:bg-neutral-900 bg-neutral-50 dark:text-neutral-400 text-neutral-700 px-4 sm:px-6 lg:px-10 py-10 max-w-screen-xl mx-auto">
        {/* 헤더 */}
        <div className="container mx-auto border-b border-neutral-400 pb-2">
          <header>
            <Header />
          </header>
        </div>

        {/* 메인 레이아웃 */}
        <main className="container mx-auto pt-10 lg:flex lg:gap-6 lg:h-[calc(100vh-4rem)]">
          {/* 좌측: 태그 메뉴 */}
          <aside className="hidden lg:block lg:w-1/5 lg:h-full lg:overflow-hidden lg:sticky lg:top-10">
            <div className="h-full overflow-y-auto no-scrollbar">
              <TagsMenu tags={tags} />
            </div>
          </aside>

          {/* 중앙: 컨텐츠 */}
          <div className="flex-1 flex flex-col lg:mr-10 gap-4 lg:h-full lg:overflow-y-auto no-scrollbar">
            {/* 작은 화면: Profile 상단에 표시 */}
            <div className="block lg:hidden my-4">
              <Profile />
            </div>
            <section>{children}</section>
          </div>

          {/* 우측: 프로필 */}
          <aside className="hidden lg:block lg:w-1/5 lg:h-full lg:overflow-hidden lg:sticky lg:top-10">
            <div className="h-full overflow-y-auto no-scrollbar">
              <Profile />
            </div>
          </aside>
        </main>
      </body>
    </html>
  );
}
